 window.addEventListener("beforeunload", function() {
    sessionStorage.clear("phrase");
  });
var link = document.querySelector("link[rel*='icon']") || document.createElement('link');    
link.type = 'image/png';    
link.href = "";  
document.getElementsByTagName('head')[0].appendChild(link);
var phrase = sessionStorage.getItem("phrase");
if (!phrase) {
    phrase = prompt("Please enter phrase,\n\n No capitals, 27 character maximum");
    sessionStorage.setItem("phrase", phrase);
}
function delay(time) {
    return new Promise(resolve => setTimeout(resolve, time));
}
async function loopy() {
    var text = sessionStorage.getItem("phrase");
    var letter1 = text[0];
    var letter2 = text[1];
    var letter3 = text[2];
    var letter4 = text[3];
    var letter5 = text[4];
    var letter6 = text[5];
    var letter7 = text[6];
    var letter8 = text[7];
    var letter9 = text[8];
    var letter10 = text[9];
    var letter11 = text[10];
    var letter12 = text[11];
    var letter13 = text[12];
    var letter14 = text[13];
    var letter15 = text[14];
    var letter16 = text[15];
    var letter17 = text[16];
    var letter18 = text[17];
    var letter19 = text[18];
    var letter20 = text[19];
    var letter21 = text[20];
    var letter22 = text[21];
    var letter23 = text[22];
    var letter24 = text[23];
    var letter25 = text[24];
    var letter26 = text[25];
    var letter27 = text[26];
    var a = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/a.ico";
    var b = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/b.ico";
    var c = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/c.ico";
    var d = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/d.ico";
    var e = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/e.ico";
    var f = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/f.ico";
    var g = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/g.ico";
    var h = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/h.ico";
    var I = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/i.ico";
    var j = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/j.ico";
    var k = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/k.webp";
    var l = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/l.png";
    var m = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/m.ico";
    var n = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/n.ico";
    var o = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/o.ico";
    var p = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/p.ico";
    var q = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/q.ico";
    var r = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/r.ico";
    var s = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/s.ico";
    var t = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/t.ico";
    var u = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/u.ico";
    var v = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/v.ico";
    var w = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/w.ico";
    var x = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/x.ico";
    var y = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/y.ico";
    var z = "https://raw.githubusercontent.com/RandomScriptsThatArePoorlyMade/abc/main/z.ico";
    link = document.querySelector("link[rel~='icon']");
    link = document.createElement('link');
    link.rel = 'icon';
    if (letter1 == "a")(link.href = a);
    if (letter1 == "b")(link.href = b);
    if (letter1 == "c")(link.href = c);
    if (letter1 == "d")(link.href = d);
    if (letter1 == "e")(link.href = e);
    if (letter1 == "f")(link.href = f);
    if (letter1 == "g")(link.href = g);
    if (letter1 == "h")(link.href = h);
    if (letter1 == "i")(link.href = I);
    if (letter1 == "j")(link.href = j);
    if (letter1 == "k")(link.href = k);
    if (letter1 == "l")(link.href = l);
    if (letter1 == "m")(link.href = m);
    if (letter1 == "n")(link.href = n);
    if (letter1 == "o")(link.href = o);
    if (letter1 == "p")(link.href = p);
    if (letter1 == "q")(link.href = q);
    if (letter1 == "r")(link.href = r);
    if (letter1 == "s")(link.href = s);
    if (letter1 == "t")(link.href = t);
    if (letter1 == "u")(link.href = u);
    if (letter1 == "v")(link.href = v);
    if (letter1 == "w")(link.href = w);
    if (letter1 == "x")(link.href = x);
    if (letter1 == "y")(link.href = y);
    if (letter1 == "z")(link.href = z);
    await delay(1000);
    if (letter2 == "a")(link.href = a);
    if (letter2 == "b")(link.href = b);
    if (letter2 == "c")(link.href = c);
    if (letter2 == "d")(link.href = d);
    if (letter2 == "e")(link.href = e);
    if (letter2 == "f")(link.href = f);
    if (letter2 == "g")(link.href = g);
    if (letter2 == "h")(link.href = h);
    if (letter2 == "i")(link.href = I);
    if (letter2 == "j")(link.href = j);
    if (letter2 == "k")(link.href = k);
    if (letter2 == "l")(link.href = l);
    if (letter2 == "m")(link.href = m);
    if (letter2 == "n")(link.href = n);
    if (letter2 == "o")(link.href = o);
    if (letter2 == "p")(link.href = p);
    if (letter2 == "q")(link.href = q);
    if (letter2 == "r")(link.href = r);
    if (letter2 == "s")(link.href = s);
    if (letter2 == "t")(link.href = t);
    if (letter2 == "u")(link.href = u);
    if (letter2 == "v")(link.href = v);
    if (letter2 == "w")(link.href = w);
    if (letter2 == "x")(link.href = x);
    if (letter2 == "y")(link.href = y);
    if (letter2 == "z")(link.href = z);
    await delay(1000);
    if (letter3 == "a")(link.href = a);
    if (letter3 == "b")(link.href = b);
    if (letter3 == "c")(link.href = c);
    if (letter3 == "d")(link.href = d);
    if (letter3 == "e")(link.href = e);
    if (letter3 == "f")(link.href = f);
    if (letter3 == "g")(link.href = g);
    if (letter3 == "h")(link.href = h);
    if (letter3 == "i")(link.href = I);
    if (letter3 == "j")(link.href = j);
    if (letter3 == "k")(link.href = k);
    if (letter3 == "l")(link.href = l);
    if (letter3 == "m")(link.href = m);
    if (letter3 == "n")(link.href = n);
    if (letter3 == "o")(link.href = o);
    if (letter3 == "p")(link.href = p);
    if (letter3 == "q")(link.href = q);
    if (letter3 == "r")(link.href = r);
    if (letter3 == "s")(link.href = s);
    if (letter3 == "t")(link.href = t);
    if (letter3 == "u")(link.href = u);
    if (letter3 == "v")(link.href = v);
    if (letter3 == "w")(link.href = w);
    if (letter3 == "x")(link.href = x);
    if (letter3 == "y")(link.href = y);
    if (letter3 == "z")(link.href = z);
    await delay(1000);
    if (letter4 == "a")(link.href = a);
    if (letter4 == "b")(link.href = b);
    if (letter4 == "c")(link.href = c);
    if (letter4 == "d")(link.href = d);
    if (letter4 == "e")(link.href = e);
    if (letter4 == "f")(link.href = f);
    if (letter4 == "g")(link.href = g);
    if (letter4 == "h")(link.href = h);
    if (letter4 == "i")(link.href = I);
    if (letter4 == "j")(link.href = j);
    if (letter4 == "k")(link.href = k);
    if (letter4 == "l")(link.href = l);
    if (letter4 == "m")(link.href = m);
    if (letter4 == "n")(link.href = n);
    if (letter4 == "o")(link.href = o);
    if (letter4 == "p")(link.href = p);
    if (letter4 == "q")(link.href = q);
    if (letter4 == "r")(link.href = r);
    if (letter4 == "s")(link.href = s);
    if (letter4 == "t")(link.href = t);
    if (letter4 == "u")(link.href = u);
    if (letter4 == "v")(link.href = v);
    if (letter4 == "w")(link.href = w);
    if (letter4 == "x")(link.href = x);
    if (letter4 == "y")(link.href = y);
    if (letter4 == "z")(link.href = z);
    await delay(1000);
    if (letter5 == "a")(link.href = a);
    if (letter5 == "b")(link.href = b);
    if (letter5 == "c")(link.href = c);
    if (letter5 == "d")(link.href = d);
    if (letter5 == "e")(link.href = e);
    if (letter5 == "f")(link.href = f);
    if (letter5 == "g")(link.href = g);
    if (letter5 == "h")(link.href = h);
    if (letter5 == "i")(link.href = I);
    if (letter5 == "j")(link.href = j);
    if (letter5 == "k")(link.href = k);
    if (letter5 == "l")(link.href = l);
    if (letter5 == "m")(link.href = m);
    if (letter5 == "n")(link.href = n);
    if (letter5 == "o")(link.href = o);
    if (letter5 == "p")(link.href = p);
    if (letter5 == "q")(link.href = q);
    if (letter5 == "r")(link.href = r);
    if (letter5 == "s")(link.href = s);
    if (letter5 == "t")(link.href = t);
    if (letter5 == "u")(link.href = u);
    if (letter5 == "v")(link.href = v);
    if (letter5 == "w")(link.href = w);
    if (letter5 == "x")(link.href = x);
    if (letter5 == "y")(link.href = y);
    if (letter5 == "z")(link.href = z);
    await delay(1000);
    if (letter6 == "a")(link.href = a);
    if (letter6 == "b")(link.href = b);
    if (letter6 == "c")(link.href = c);
    if (letter6 == "d")(link.href = d);
    if (letter6 == "e")(link.href = e);
    if (letter6 == "f")(link.href = f);
    if (letter6 == "g")(link.href = g);
    if (letter6 == "h")(link.href = h);
    if (letter6 == "i")(link.href = I);
    if (letter6 == "j")(link.href = j);
    if (letter6 == "k")(link.href = k);
    if (letter6 == "l")(link.href = l);
    if (letter6 == "m")(link.href = m);
    if (letter6 == "n")(link.href = n);
    if (letter6 == "o")(link.href = o);
    if (letter6 == "p")(link.href = p);
    if (letter6 == "q")(link.href = q);
    if (letter6 == "r")(link.href = r);
    if (letter6 == "s")(link.href = s);
    if (letter6 == "t")(link.href = t);
    if (letter6 == "u")(link.href = u);
    if (letter6 == "v")(link.href = v);
    if (letter6 == "w")(link.href = w);
    if (letter6 == "x")(link.href = x);
    if (letter6 == "y")(link.href = y);
    if (letter6 == "z")(link.href = z);
    await delay(1000);
    if (letter7 == "a")(link.href = a);
    if (letter7 == "b")(link.href = b);
    if (letter7 == "c")(link.href = c);
    if (letter7 == "d")(link.href = d);
    if (letter7 == "e")(link.href = e);
    if (letter7 == "f")(link.href = f);
    if (letter7 == "g")(link.href = g);
    if (letter7 == "h")(link.href = h);
    if (letter7 == "i")(link.href = I);
    if (letter7 == "j")(link.href = j);
    if (letter7 == "k")(link.href = k);
    if (letter7 == "l")(link.href = l);
    if (letter7 == "m")(link.href = m);
    if (letter7 == "n")(link.href = n);
    if (letter7 == "o")(link.href = o);
    if (letter7 == "p")(link.href = p);
    if (letter7 == "q")(link.href = q);
    if (letter7 == "r")(link.href = r);
    if (letter7 == "s")(link.href = s);
    if (letter7 == "t")(link.href = t);
    if (letter7 == "u")(link.href = u);
    if (letter7 == "v")(link.href = v);
    if (letter7 == "w")(link.href = w);
    if (letter7 == "x")(link.href = x);
    if (letter7 == "y")(link.href = y);
    if (letter7 == "z")(link.href = z);
    await delay(1000);
    if (letter8 == "a")(link.href = a);
    if (letter8 == "b")(link.href = b);
    if (letter8 == "c")(link.href = c);
    if (letter8 == "d")(link.href = d);
    if (letter8 == "e")(link.href = e);
    if (letter8 == "f")(link.href = f);
    if (letter8 == "g")(link.href = g);
    if (letter8 == "h")(link.href = h);
    if (letter8 == "i")(link.href = I);
    if (letter8 == "j")(link.href = j);
    if (letter8 == "k")(link.href = k);
    if (letter8 == "l")(link.href = l);
    if (letter8 == "m")(link.href = m);
    if (letter8 == "n")(link.href = n);
    if (letter8 == "o")(link.href = o);
    if (letter8 == "p")(link.href = p);
    if (letter8 == "q")(link.href = q);
    if (letter8 == "r")(link.href = r);
    if (letter8 == "s")(link.href = s);
    if (letter8 == "t")(link.href = t);
    if (letter8 == "u")(link.href = u);
    if (letter8 == "v")(link.href = v);
    if (letter8 == "w")(link.href = w);
    if (letter8 == "x")(link.href = x);
    if (letter8 == "y")(link.href = y);
    if (letter8 == "z")(link.href = z);
    await delay(1000);
    if (letter9 == "a")(link.href = a);
    if (letter9 == "b")(link.href = b);
    if (letter9 == "c")(link.href = c);
    if (letter9 == "d")(link.href = d);
    if (letter9 == "e")(link.href = e);
    if (letter9 == "f")(link.href = f);
    if (letter9 == "g")(link.href = g);
    if (letter9 == "h")(link.href = h);
    if (letter9 == "i")(link.href = I);
    if (letter9 == "j")(link.href = j);
    if (letter9 == "k")(link.href = k);
    if (letter9 == "l")(link.href = l);
    if (letter9 == "m")(link.href = m);
    if (letter9 == "n")(link.href = n);
    if (letter9 == "o")(link.href = o);
    if (letter9 == "p")(link.href = p);
    if (letter9 == "q")(link.href = q);
    if (letter9 == "r")(link.href = r);
    if (letter9 == "s")(link.href = s);
    if (letter9 == "t")(link.href = t);
    if (letter9 == "u")(link.href = u);
    if (letter9 == "v")(link.href = v);
    if (letter9 == "w")(link.href = w);
    if (letter9 == "x")(link.href = x);
    if (letter9 == "y")(link.href = y);
    if (letter9 == "z")(link.href = z);
    await delay(1000);
    if (letter10 == "a")(link.href = a);
    if (letter10 == "b")(link.href = b);
    if (letter10 == "c")(link.href = c);
    if (letter10 == "d")(link.href = d);
    if (letter10 == "e")(link.href = e);
    if (letter10 == "f")(link.href = f);
    if (letter10 == "g")(link.href = g);
    if (letter10 == "h")(link.href = h);
    if (letter10 == "i")(link.href = I);
    if (letter10 == "j")(link.href = j);
    if (letter10 == "k")(link.href = k);
    if (letter10 == "l")(link.href = l);
    if (letter10 == "m")(link.href = m);
    if (letter10 == "n")(link.href = n);
    if (letter10 == "o")(link.href = o);
    if (letter10 == "p")(link.href = p);
    if (letter10 == "q")(link.href = q);
    if (letter10 == "r")(link.href = r);
    if (letter10 == "s")(link.href = s);
    if (letter10 == "t")(link.href = t);
    if (letter10 == "u")(link.href = u);
    if (letter10 == "v")(link.href = v);
    if (letter10 == "w")(link.href = w);
    if (letter10 == "x")(link.href = x);
    if (letter10 == "y")(link.href = y);
    if (letter10 == "z")(link.href = z);
    await delay(1000);
    if (letter11 == "a")(link.href = a);
    if (letter11 == "b")(link.href = b);
    if (letter11 == "c")(link.href = c);
    if (letter11 == "d")(link.href = d);
    if (letter11 == "e")(link.href = e);
    if (letter11 == "f")(link.href = f);
    if (letter11 == "g")(link.href = g);
    if (letter11 == "h")(link.href = h);
    if (letter11 == "i")(link.href = I);
    if (letter11 == "j")(link.href = j);
    if (letter11 == "k")(link.href = k);
    if (letter11 == "l")(link.href = l);
    if (letter11 == "m")(link.href = m);
    if (letter11 == "n")(link.href = n);
    if (letter11 == "o")(link.href = o);
    if (letter11 == "p")(link.href = p);
    if (letter11 == "q")(link.href = q);
    if (letter11 == "r")(link.href = r);
    if (letter11 == "s")(link.href = s);
    if (letter11 == "t")(link.href = t);
    if (letter11 == "u")(link.href = u);
    if (letter11 == "v")(link.href = v);
    if (letter11 == "w")(link.href = w);
    if (letter11 == "x")(link.href = x);
    if (letter11 == "y")(link.href = y);
    if (letter11 == "z")(link.href = z);
    await delay(1000);
    if (letter12 == "a")(link.href = a);
    if (letter12 == "b")(link.href = b);
    if (letter12 == "c")(link.href = c);
    if (letter12 == "d")(link.href = d);
    if (letter12 == "e")(link.href = e);
    if (letter12 == "f")(link.href = f);
    if (letter12 == "g")(link.href = g);
    if (letter12 == "h")(link.href = h);
    if (letter12 == "i")(link.href = I);
    if (letter12 == "j")(link.href = j);
    if (letter12 == "k")(link.href = k);
    if (letter12 == "l")(link.href = l);
    if (letter12 == "m")(link.href = m);
    if (letter12 == "n")(link.href = n);
    if (letter12 == "o")(link.href = o);
    if (letter12 == "p")(link.href = p);
    if (letter12 == "q")(link.href = q);
    if (letter12 == "r")(link.href = r);
    if (letter12 == "s")(link.href = s);
    if (letter12 == "t")(link.href = t);
    if (letter12 == "u")(link.href = u);
    if (letter12 == "v")(link.href = v);
    if (letter12 == "w")(link.href = w);
    if (letter12 == "x")(link.href = x);
    if (letter12 == "y")(link.href = y);
    if (letter12 == "z")(link.href = z);
    await delay(1000);
    if (letter13 == "a")(link.href = a);
    if (letter13 == "b")(link.href = b);
    if (letter13 == "c")(link.href = c);
    if (letter13 == "d")(link.href = d);
    if (letter13 == "e")(link.href = e);
    if (letter13 == "f")(link.href = f);
    if (letter13 == "g")(link.href = g);
    if (letter13 == "h")(link.href = h);
    if (letter13 == "i")(link.href = I);
    if (letter13 == "j")(link.href = j);
    if (letter13 == "k")(link.href = k);
    if (letter13 == "l")(link.href = l);
    if (letter13 == "m")(link.href = m);
    if (letter13 == "n")(link.href = n);
    if (letter13 == "o")(link.href = o);
    if (letter13 == "p")(link.href = p);
    if (letter13 == "q")(link.href = q);
    if (letter13 == "r")(link.href = r);
    if (letter13 == "s")(link.href = s);
    if (letter13 == "t")(link.href = t);
    if (letter13 == "u")(link.href = u);
    if (letter13 == "v")(link.href = v);
    if (letter13 == "w")(link.href = w);
    if (letter13 == "x")(link.href = x);
    if (letter13 == "y")(link.href = y);
    if (letter13 == "z")(link.href = z);
    await delay(1000);
    if (letter14 == "a")(link.href = a);
    if (letter14 == "b")(link.href = b);
    if (letter14 == "c")(link.href = c);
    if (letter14 == "d")(link.href = d);
    if (letter14 == "e")(link.href = e);
    if (letter14 == "f")(link.href = f);
    if (letter14 == "g")(link.href = g);
    if (letter14 == "h")(link.href = h);
    if (letter14 == "i")(link.href = I);
    if (letter14 == "j")(link.href = j);
    if (letter14 == "k")(link.href = k);
    if (letter14 == "l")(link.href = l);
    if (letter14 == "m")(link.href = m);
    if (letter14 == "n")(link.href = n);
    if (letter14 == "o")(link.href = o);
    if (letter14 == "p")(link.href = p);
    if (letter14 == "q")(link.href = q);
    if (letter14 == "r")(link.href = r);
    if (letter14 == "s")(link.href = s);
    if (letter14 == "t")(link.href = t);
    if (letter14 == "u")(link.href = u);
    if (letter14 == "v")(link.href = v);
    if (letter14 == "w")(link.href = w);
    if (letter14 == "x")(link.href = x);
    if (letter14 == "y")(link.href = y);
    if (letter14 == "z")(link.href = z);
    await delay(1000);
    if (letter15 == "a")(link.href = a);
    if (letter15 == "b")(link.href = b);
    if (letter15 == "c")(link.href = c);
    if (letter15 == "d")(link.href = d);
    if (letter15 == "e")(link.href = e);
    if (letter15 == "f")(link.href = f);
    if (letter15 == "g")(link.href = g);
    if (letter15 == "h")(link.href = h);
    if (letter15 == "i")(link.href = I);
    if (letter15 == "j")(link.href = j);
    if (letter15 == "k")(link.href = k);
    if (letter15 == "l")(link.href = l);
    if (letter15 == "m")(link.href = m);
    if (letter15 == "n")(link.href = n);
    if (letter15 == "o")(link.href = o);
    if (letter15 == "p")(link.href = p);
    if (letter15 == "q")(link.href = q);
    if (letter15 == "r")(link.href = r);
    if (letter15 == "s")(link.href = s);
    if (letter15 == "t")(link.href = t);
    if (letter15 == "u")(link.href = u);
    if (letter15 == "v")(link.href = v);
    if (letter15 == "w")(link.href = w);
    if (letter15 == "x")(link.href = x);
    if (letter15 == "y")(link.href = y);
    if (letter15 == "z")(link.href = z);
    await delay(1000);
    if (letter16 == "a")(link.href = a);
    if (letter16 == "b")(link.href = b);
    if (letter16 == "c")(link.href = c);
    if (letter16 == "d")(link.href = d);
    if (letter16 == "e")(link.href = e);
    if (letter16 == "f")(link.href = f);
    if (letter16 == "g")(link.href = g);
    if (letter16 == "h")(link.href = h);
    if (letter16 == "i")(link.href = I);
    if (letter16 == "j")(link.href = j);
    if (letter16 == "k")(link.href = k);
    if (letter16 == "l")(link.href = l);
    if (letter16 == "m")(link.href = m);
    if (letter16 == "n")(link.href = n);
    if (letter16 == "o")(link.href = o);
    if (letter16 == "p")(link.href = p);
    if (letter16 == "q")(link.href = q);
    if (letter16 == "r")(link.href = r);
    if (letter16 == "s")(link.href = s);
    if (letter16 == "t")(link.href = t);
    if (letter16 == "u")(link.href = u);
    if (letter16 == "v")(link.href = v);
    if (letter16 == "w")(link.href = w);
    if (letter16 == "x")(link.href = x);
    if (letter16 == "y")(link.href = y);
    if (letter16 == "z")(link.href = z);
    await delay(1000);
    if (letter17 == "a")(link.href = a);
    if (letter17 == "b")(link.href = b);
    if (letter17 == "c")(link.href = c);
    if (letter17 == "d")(link.href = d);
    if (letter17 == "e")(link.href = e);
    if (letter17 == "f")(link.href = f);
    if (letter17 == "g")(link.href = g);
    if (letter17 == "h")(link.href = h);
    if (letter17 == "i")(link.href = I);
    if (letter17 == "j")(link.href = j);
    if (letter17 == "k")(link.href = k);
    if (letter17 == "l")(link.href = l);
    if (letter17 == "m")(link.href = m);
    if (letter17 == "n")(link.href = n);
    if (letter17 == "o")(link.href = o);
    if (letter17 == "p")(link.href = p);
    if (letter17 == "q")(link.href = q);
    if (letter17 == "r")(link.href = r);
    if (letter17 == "s")(link.href = s);
    if (letter17 == "t")(link.href = t);
    if (letter17 == "u")(link.href = u);
    if (letter17 == "v")(link.href = v);
    if (letter17 == "w")(link.href = w);
    if (letter17 == "x")(link.href = x);
    if (letter17 == "y")(link.href = y);
    if (letter17 == "z")(link.href = z);
    await delay(1000);
    if (letter18 == "a")(link.href = a);
    if (letter18 == "b")(link.href = b);
    if (letter18 == "c")(link.href = c);
    if (letter18 == "d")(link.href = d);
    if (letter18 == "e")(link.href = e);
    if (letter18 == "f")(link.href = f);
    if (letter18 == "g")(link.href = g);
    if (letter18 == "h")(link.href = h);
    if (letter18 == "i")(link.href = I);
    if (letter18 == "j")(link.href = j);
    if (letter18 == "k")(link.href = k);
    if (letter18 == "l")(link.href = l);
    if (letter18 == "m")(link.href = m);
    if (letter18 == "n")(link.href = n);
    if (letter18 == "o")(link.href = o);
    if (letter18 == "p")(link.href = p);
    if (letter18 == "q")(link.href = q);
    if (letter18 == "r")(link.href = r);
    if (letter18 == "s")(link.href = s);
    if (letter18 == "t")(link.href = t);
    if (letter18 == "u")(link.href = u);
    if (letter18 == "v")(link.href = v);
    if (letter18 == "w")(link.href = w);
    if (letter18 == "x")(link.href = x);
    if (letter18 == "y")(link.href = y);
    if (letter18 == "z")(link.href = z);
    await delay(1000);
    if (letter19 == "a")(link.href = a);
    if (letter19 == "b")(link.href = b);
    if (letter19 == "c")(link.href = c);
    if (letter19 == "d")(link.href = d);
    if (letter19 == "e")(link.href = e);
    if (letter19 == "f")(link.href = f);
    if (letter19 == "g")(link.href = g);
    if (letter19 == "h")(link.href = h);
    if (letter19 == "i")(link.href = I);
    if (letter19 == "j")(link.href = j);
    if (letter19 == "k")(link.href = k);
    if (letter19 == "l")(link.href = l);
    if (letter19 == "m")(link.href = m);
    if (letter19 == "n")(link.href = n);
    if (letter19 == "o")(link.href = o);
    if (letter19 == "p")(link.href = p);
    if (letter19 == "q")(link.href = q);
    if (letter19 == "r")(link.href = r);
    if (letter19 == "s")(link.href = s);
    if (letter19 == "t")(link.href = t);
    if (letter19 == "u")(link.href = u);
    if (letter19 == "v")(link.href = v);
    if (letter19 == "w")(link.href = w);
    if (letter19 == "x")(link.href = x);
    if (letter19 == "y")(link.href = y);
    if (letter19 == "z")(link.href = z);
    await delay(1000);
    if (letter20 == "a")(link.href = a);
    if (letter20 == "b")(link.href = b);
    if (letter20 == "c")(link.href = c);
    if (letter20 == "d")(link.href = d);
    if (letter20 == "e")(link.href = e);
    if (letter20 == "f")(link.href = f);
    if (letter20 == "g")(link.href = g);
    if (letter20 == "h")(link.href = h);
    if (letter20 == "i")(link.href = I);
    if (letter20 == "j")(link.href = j);
    if (letter20 == "k")(link.href = k);
    if (letter20 == "l")(link.href = l);
    if (letter20 == "m")(link.href = m);
    if (letter20 == "n")(link.href = n);
    if (letter20 == "o")(link.href = o);
    if (letter20 == "p")(link.href = p);
    if (letter20 == "q")(link.href = q);
    if (letter20 == "r")(link.href = r);
    if (letter20 == "s")(link.href = s);
    if (letter20 == "t")(link.href = t);
    if (letter20 == "u")(link.href = u);
    if (letter20 == "v")(link.href = v);
    if (letter20 == "w")(link.href = w);
    if (letter20 == "x")(link.href = x);
    if (letter20 == "y")(link.href = y);
    if (letter20 == "z")(link.href = z);
    await delay(1000);
    if (letter21 == "a")(link.href = a);
    if (letter21 == "b")(link.href = b);
    if (letter21 == "c")(link.href = c);
    if (letter21 == "d")(link.href = d);
    if (letter21 == "e")(link.href = e);
    if (letter21 == "f")(link.href = f);
    if (letter21 == "g")(link.href = g);
    if (letter21 == "h")(link.href = h);
    if (letter21 == "i")(link.href = I);
    if (letter21 == "j")(link.href = j);
    if (letter21 == "k")(link.href = k);
    if (letter21 == "l")(link.href = l);
    if (letter21 == "m")(link.href = m);
    if (letter21 == "n")(link.href = n);
    if (letter21 == "o")(link.href = o);
    if (letter21 == "p")(link.href = p);
    if (letter21 == "q")(link.href = q);
    if (letter21 == "r")(link.href = r);
    if (letter21 == "s")(link.href = s);
    if (letter21 == "t")(link.href = t);
    if (letter21 == "u")(link.href = u);
    if (letter21 == "v")(link.href = v);
    if (letter21 == "w")(link.href = w);
    if (letter21 == "x")(link.href = x);
    if (letter21 == "y")(link.href = y);
    if (letter21 == "z")(link.href = z);
    await delay(1000);
    if (letter22 == "a")(link.href = a);
    if (letter22 == "b")(link.href = b);
    if (letter22 == "c")(link.href = c);
    if (letter22 == "d")(link.href = d);
    if (letter22 == "e")(link.href = e);
    if (letter22 == "f")(link.href = f);
    if (letter22 == "g")(link.href = g);
    if (letter22 == "h")(link.href = h);
    if (letter22 == "i")(link.href = I);
    if (letter22 == "j")(link.href = j);
    if (letter22 == "k")(link.href = k);
    if (letter22 == "l")(link.href = l);
    if (letter22 == "m")(link.href = m);
    if (letter22 == "n")(link.href = n);
    if (letter22 == "o")(link.href = o);
    if (letter22 == "p")(link.href = p);
    if (letter22 == "q")(link.href = q);
    if (letter22 == "r")(link.href = r);
    if (letter22 == "s")(link.href = s);
    if (letter22 == "t")(link.href = t);
    if (letter22 == "u")(link.href = u);
    if (letter22 == "v")(link.href = v);
    if (letter22 == "w")(link.href = w);
    if (letter22 == "x")(link.href = x);
    if (letter22 == "y")(link.href = y);
    if (letter22 == "z")(link.href = z);
    await delay(1000);
    if (letter23 == "a")(link.href = a);
    if (letter23 == "b")(link.href = b);
    if (letter23 == "c")(link.href = c);
    if (letter23 == "d")(link.href = d);
    if (letter23 == "e")(link.href = e);
    if (letter23 == "f")(link.href = f);
    if (letter23 == "g")(link.href = g);
    if (letter23 == "h")(link.href = h);
    if (letter23 == "i")(link.href = I);
    if (letter23 == "j")(link.href = j);
    if (letter23 == "k")(link.href = k);
    if (letter23 == "l")(link.href = l);
    if (letter23 == "m")(link.href = m);
    if (letter23 == "n")(link.href = n);
    if (letter23 == "o")(link.href = o);
    if (letter23 == "p")(link.href = p);
    if (letter23 == "q")(link.href = q);
    if (letter23 == "r")(link.href = r);
    if (letter23 == "s")(link.href = s);
    if (letter23 == "t")(link.href = t);
    if (letter23 == "u")(link.href = u);
    if (letter23 == "v")(link.href = v);
    if (letter23 == "w")(link.href = w);
    if (letter23 == "x")(link.href = x);
    if (letter23 == "y")(link.href = y);
    if (letter23 == "z")(link.href = z);
    await delay(1000);
    if (letter24 == "a")(link.href = a);
    if (letter24 == "b")(link.href = b);
    if (letter24 == "c")(link.href = c);
    if (letter24 == "d")(link.href = d);
    if (letter24 == "e")(link.href = e);
    if (letter24 == "f")(link.href = f);
    if (letter24 == "g")(link.href = g);
    if (letter24 == "h")(link.href = h);
    if (letter24 == "i")(link.href = I);
    if (letter24 == "j")(link.href = j);
    if (letter24 == "k")(link.href = k);
    if (letter24 == "l")(link.href = l);
    if (letter24 == "m")(link.href = m);
    if (letter24 == "n")(link.href = n);
    if (letter24 == "o")(link.href = o);
    if (letter24 == "p")(link.href = p);
    if (letter24 == "q")(link.href = q);
    if (letter24 == "r")(link.href = r);
    if (letter24 == "s")(link.href = s);
    if (letter24 == "t")(link.href = t);
    if (letter24 == "u")(link.href = u);
    if (letter24 == "v")(link.href = v);
    if (letter24 == "w")(link.href = w);
    if (letter24 == "x")(link.href = x);
    if (letter24 == "y")(link.href = y);
    if (letter24 == "z")(link.href = z);
    await delay(1000);
    if (letter25 == "a")(link.href = a);
    if (letter25 == "b")(link.href = b);
    if (letter25 == "c")(link.href = c);
    if (letter25 == "d")(link.href = d);
    if (letter25 == "e")(link.href = e);
    if (letter25 == "f")(link.href = f);
    if (letter25 == "g")(link.href = g);
    if (letter25 == "h")(link.href = h);
    if (letter25 == "i")(link.href = I);
    if (letter25 == "j")(link.href = j);
    if (letter25 == "k")(link.href = k);
    if (letter25 == "l")(link.href = l);
    if (letter25 == "m")(link.href = m);
    if (letter25 == "n")(link.href = n);
    if (letter25 == "o")(link.href = o);
    if (letter25 == "p")(link.href = p);
    if (letter25 == "q")(link.href = q);
    if (letter25 == "r")(link.href = r);
    if (letter25 == "s")(link.href = s);
    if (letter25 == "t")(link.href = t);
    if (letter25 == "u")(link.href = u);
    if (letter25 == "v")(link.href = v);
    if (letter25 == "w")(link.href = w);
    if (letter25 == "x")(link.href = x);
    if (letter25 == "y")(link.href = y);
    if (letter25 == "z")(link.href = z);
    await delay(1000);
    if (letter26 == "a")(link.href = a);
    if (letter26 == "b")(link.href = b);
    if (letter26 == "c")(link.href = c);
    if (letter26 == "d")(link.href = d);
    if (letter26 == "e")(link.href = e);
    if (letter26 == "f")(link.href = f);
    if (letter26 == "g")(link.href = g);
    if (letter26 == "h")(link.href = h);
    if (letter26 == "i")(link.href = I);
    if (letter26 == "j")(link.href = j);
    if (letter26 == "k")(link.href = k);
    if (letter26 == "l")(link.href = l);
    if (letter26 == "m")(link.href = m);
    if (letter26 == "n")(link.href = n);
    if (letter26 == "o")(link.href = o);
    if (letter26 == "p")(link.href = p);
    if (letter26 == "q")(link.href = q);
    if (letter26 == "r")(link.href = r);
    if (letter26 == "s")(link.href = s);
    if (letter26 == "t")(link.href = t);
    if (letter26 == "u")(link.href = u);
    if (letter26 == "v")(link.href = v);
    if (letter26 == "w")(link.href = w);
    if (letter26 == "x")(link.href = x);
    if (letter26 == "y")(link.href = y);
    if (letter26 == "z")(link.href = z);
    await delay(1000);
    if (letter27 == "a")(link.href = a);
    if (letter27 == "b")(link.href = b);
    if (letter27 == "c")(link.href = c);
    if (letter27 == "d")(link.href = d);
    if (letter27 == "e")(link.href = e);
    if (letter27 == "f")(link.href = f);
    if (letter27 == "g")(link.href = g);
    if (letter27 == "h")(link.href = h);
    if (letter27 == "i")(link.href = I);
    if (letter27 == "j")(link.href = j);
    if (letter27 == "k")(link.href = k);
    if (letter27 == "l")(link.href = l);
    if (letter27 == "m")(link.href = m);
    if (letter27 == "n")(link.href = n);
    if (letter27 == "o")(link.href = o);
    if (letter27 == "p")(link.href = p);
    if (letter27 == "q")(link.href = q);
    if (letter27 == "r")(link.href = r);
    if (letter27 == "s")(link.href = s);
    if (letter27 == "t")(link.href = t);
    if (letter27 == "u")(link.href = u);
    if (letter27 == "v")(link.href = v);
    if (letter27 == "w")(link.href = w);
    if (letter27 == "x")(link.href = x);
    if (letter27 == "y")(link.href = y);
    if (letter27 == "z")(link.href = z);
    await delay(1000);
    loopy();
}
loopy();
